import MainNav from "./components/navigation/MainNav";
import "./globals.css";
import { Comfortaa } from "next/font/google";

const comfort = Comfortaa({ subsets: ["latin"] });

export const metadata = {
  title: "Imperial Studios",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={comfort.className}>
        <MainNav />
        {children}
        <script src="https://unpkg.com/taos@1.0.5/dist/taos.js"></script>
      </body>
    </html>
  );
}
